# Don't change these
theme: jekyll-theme-primer
spec_server: specs.amwa.tv

# AMWA ID
amwa_id: BCP-004-01

# Base name for site (typically lower case version of AMWA ID, or the repo name)
baseurl: /bcp-004-01

# Which release or branch appears in header links and on the home page
default_tree: releases/v1.0.0

# Regex patterns of releases and branches to show
show_releases: ^v[0-9]+\.[0-9]+$|^v[0-9]+\.[0-9]+\.[0-9]+$
show_branches: ^v[0-9]+\.[0-9]+-dev$|^v[0-9]+\.[0-9]+\.x$|^publish-
